url: http://airquill.io
name: AirQuill
authorName: Tiese Barrell
authorEmail: info@mazidea.com

markdown: kramdown
highlighter: pygments

safe: true
gems:
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap

tagline:  Presumptuous tagline goes here