safe: true
pygments: true
url: http://tiesebarrell.github.io
name: AirQuill
tagline:  Presumptuous tagline goes here
authorName: Tiese Barrell
authorEmail: info@mazidea.com
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap