safe: true
url: http://tiesebarrell.github.io
name: AirQuill
tagline:  Presumptuous tagline goes here
author: 
 - name: Tiese Barrell
 - email: info@mazidea.com
gems:
 - jekyll-mentions
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap
