safe: true
highlighter: pygments
url: http://airquill.io
name: AirQuill
tagline:  Presumptuous tagline goes here
authorName: Tiese Barrell
authorEmail: info@mazidea.com
gems:
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap
markdown: kramdown