url: http://airquill.io
name: AirQuill
authorName: Tiese Barrell
authorEmail: info@mazidea.com

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:slug/

safe: true
plugins:
 - jemoji
 - jekyll-redirect-from
 - jekyll-sitemap

whitelist:
- jekyll-redirect-from

tagline: Presumptuous tagline goes here

kramdown:
  parse_block_html: true

exclude: [
  "assets/styles/*.less",
  "assets/styles/airquill.css",
  "assets/javascript/airquill.js",
  "assets/javascript/airquill-core.js",
  "assets/javascript/airquill-nav.js",
  "assets/javascript/airquill-preferences.js",
  "assets/javascript/airquill-theme.js",
  "assets/javascript/airquill.js.less",
  "assets/images/*.svg",
  "node_modules"
]