version: '3'

services:
  jekyll:
    image: starefossen/github-pages:latest
    container_name: airquill.io
    environment:
    - JEKYLL_ENV=docker
    # force_polling makes the linux box watch for any changes to files, then it will regenerate
    # livereload gets the browser to automatically refresh when changes happen to files
    # incremental is disabled because it is an experimental feature for jekyll 3.8 and causes livereload to stop working
    #command: jekyll serve --force_polling --livereload
    ports:
    - 4000:4000
    - 35729:35729
    volumes:
    - ./:/usr/src/app:delegated